var data = {
  '1': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '2': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '3': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '4': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '5': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '6': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '7': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '8': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '9': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '10': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '11': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '12': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '13': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '14': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '15': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '16': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '17': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '18': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '19': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '20': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '21': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '22': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '23': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '24': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '25': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '26': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '27': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '28': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '29': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '30': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '31': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '32': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '33': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '34': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '35': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
  '36': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
};
