var data = {
  '1': {
    question: 'Name of the twitter logo bird?',
    "url":"qus-1-images/1.png",
    '1': 'Social bird',
    '2': 'Larry T bird',
    '3': 'Biz the bird',
    '4': 'twitter bird',
     'ans': '2',
  },
  '2': {
    question: 'BMW logo colors represents?',
    "url":"qus-1-images/2.png",
    '1': 'Air plane propeller',
    '2': 'Colors of Bavaria',
    '3': 'Balance of style and speed',
    '4': 'None of the above',
     'ans': '2',
  },
  '3': {
    question: 'What does L in Google represent?',
    "url":"qus-1-images/3.png",
    '1': 'Breaking rules and having fun',
    '2': 'Down to earth',
    '3': 'Eco-friendly',
    '4': 'Perfection in all',
     'ans': '1',
  },
  '4': {
    question: 'DETESTABLE',
    '1': 'Awful',
    '2': 'Innocuous',
    '3': 'Inoffensive',
    '4': 'Plenty',
     'ans': '1',
  },
  '5': {
    question: 'BENIGN',
    '1': 'Bad',
    '2': 'Mischievous',
    '3': 'Gentle',
    '4': 'Detrimental',
     'ans': '3',
  },
  '6': {
    question: 'RETRIBUTION',
    '1': 'forgiveness',
    '2': 'lenity',
    '3': 'grace',
    '4': 'payback',
     'ans': '4',
  },
  '7': {
    question: 'To come back',
    '1': 'Advance',
    '2': 'Revert',
    '3': 'Evolve',
    '4': 'Progress',
     'ans': '2',
  },
  '8': {
    question: 'To accumulate',
    '1': 'Accrue',
    '2': 'Dwindle ',
    '3': 'Lessen',
    '4': 'Lose ',
     'ans': '1',
  },
  '9': {
    question: 'To take unfair advantage of ',
    '1': 'Utilize',
    '2': 'Exploit',
    '3': 'Idleness',
    '4': 'Inaction',
     'ans': '2',
  },
  '10': {
    question: 'From Julius Caesar',
    "url":"qus-1-images/10.png",
    '1': 'Et tu, Brute?',
    '2': 'Caesar, now be still',
    '3': 'It was Greek to me',
    '4': ' Veni Vidi Amavi',
     'ans': '1',
  },
  '11': {
    question: 'From Oscar wilde',
    "url":"qus-1-images/11.png",
    '1': 'The selfish giant',
    '2': 'The giant and the garden',
    '3': 'The lovely garden',
    '4': 'The life of the giant',
     'ans': '1',
  },
  '12': {
    question: 'Guess me?',
    "url":"qus-1-images/12.png",
    '1': 'Aurora',
    '2': 'Geomagnetic storm',
    '3': 'Northern lights',
    '4': 'Southern lights',
     'ans': '1',
  },
  '13': {
    question: 'I have no rhyme. Guess me',
    '1': 'Silver',
    '2': 'Time',
    '3': 'Age',
    '4': 'Watch',
     'ans': '1',
  },
  '14': {
    question: 'Which country doesn’t have official language',
    '1': 'Serbia',
    '2': 'USA',
    '3': 'Philippines',
    '4': 'Norway ',
     'ans': '2',
  },
  '15': {
    question: 'It represents ',
    "url":"qus-1-images/15.png",
    '1': 'Tilth',
    '2': 'Trimming',
    '3': 'Shoving',
    '4': 'Dissuade',
     'ans': '1',
  },
  '16': {
    question: 'The vowel that doesn’t exist between 0 to 999 is',
    '1': 'A',
    '2': 'E',
    '3': 'I',
    '4': 'O',
     'ans': '1',
  },
  '17': {
    question: 'The shape of the world',
    '1': 'Oblate spheroid',
    '2': 'Oblate ellipsoid',
    '3': 'Sphere',
    '4': 'Both a and b',
     'ans': '4',
  },
  '18': {
    question: '',
    "url":"qus-1-images/18.png",
    '1': 'Natant',
    '2': 'Rising',
    '3': 'Diving',
    '4': 'Submerge',
     'ans': '1',
  },
  '19': {
    question: '',
    "url":"qus-1-images/19.png",
    '1': 'Hush',
    '2': 'Squall',
    '3': 'Peace',
    '4': 'Tranquility',
     'ans': '2',
  },
  '20': {
    question: 'Which of the following country was first to use the symbol zero?',
    '1': 'Japan',
    '2': 'China',
    '3': 'UK',
    '4': 'India ',
     'ans': '4',
  },
  '21': {
    question: 'The # symbol is technically called ',
    '1': 'Octothrop ',
    '2': 'Ampersand',
    '3': 'Lozenge',
    '4': 'GT',
     'ans': '1',
  },
  '22': {
    question: 'EPIDEMIC',
    '1': 'Contagious',
    '2': 'Limited',
    '3': 'Limited',
    '4': 'Specific',
     'ans': '1',
  },
  '23': {
    question: 'CONFESS',
    '1': 'Acknowledge',
    '2': 'Deny',
    '3': 'Submit',
    '4': 'Counter',
     'ans': '1',
  },
  '24': {
    question: 'To pay attention',
    '1': 'Ignore',
    '2': 'Heed',
    '3': 'Tune out',
    '4': 'Disregard',
     'ans': '2',
  },
  '25': {
    question: 'Expression of high regard',
    '1': 'Contempt',
    '2': 'Criticize',
    '3': 'Treason',
    '4': 'Homage',
     'ans': '4',
  },
  '26': {
    question: '',
    "url":"qus-1-images/26.png",
    '1': 'Sprint',
    '2': 'Drag',
    '3': 'Creep',
    '4': 'Limp',
     'ans': '1',
  },
  '27': {
    question: '',
    "url":"qus-1-images/27.png",
    '1': 'Concise',
    '2': 'Gale',
    '3': 'Pleasant',
    '4': 'Calm',
     'ans': '2',
  },
  '28': {
    question: 'Lover of learning',
    '1': 'Hodophile',
    '2': 'Philomath',
    '3': 'Melophile',
    '4': 'Ornithophile',
     'ans': '2',
  },
  '29': {
    question: '',
    "url":"qus-1-images/29.png",
    '1': 'Ophidiophobia',
    '2': 'Nosophobia',
    '3': 'Thanatophobia',
    '4': 'Nyctophobia',
     'ans': '1',
  },
  '30': {
    question: ' HIT ME UP ',
    '1': 'Spend time',
    '2': 'Contact me',
    '3': 'To beat someone up',
    '4': 'To meet',
     'ans': '2',
  },
  '31': {
    question: 'means',
    "url":"qus-1-images/31.png",
    '1': 'Interrobang',
    '2': 'Otimes',
    '3': 'Notin',
    '4': 'Propto',
     'ans': '1',
  },
  '32': {
    question: 'Correct Me',
    '1': 'Peculier',
    '2': 'Peculiar',
    '3': 'Peaculiar',
    '4': 'Pecueliar',
     'ans': '2',
  },
  '33': {
    question: 'BREAK A LEG',
    '1': 'Get out of control',
    '2': 'Sick',
    '3': 'Good luck',
    '4': 'Beat up',
     'ans': '3',
  },
  '34': {
    question: 'STAND UP',
    '1': 'Do nothing',
    '2': 'Rise in position',
    '3': 'Support',
    '4': 'Back up',
     'ans': '1',
  },
  '35': {
    question: 'Correct Me',
    '1': 'Lieutonant',
    '2': 'Lieutenant',
    '3': 'Liuetinant',
    '4': 'liutenant',
     'ans': '2',
  },
  '36': {
    question: 'What is your name?',
    '1': 'Udaya',
    '2': 'Vivek',
    '3': 'Akassh',
    '4': 'Google',
     'ans': '1',
  },
};
